
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/sessionwrapper";
export const metadata = {
  title: "Fitness Empire",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
        <Navbar/>
        {children}
        <Footer/>
        </SessionWrapper>
      </body>
    </html>
  );
}
